language: groovy
jdk:
  - oraclejdk7
script: ./grailsw refresh-dependencies
	&& ./grailsw test-app
deploy:
  provider: heroku
  api_key:
    secure: fozTdn36Whq5MevDsq6LzvsmP/eCtFlK2xpJkoopq3erO87oa5vn7CQUTKJ31t5Emjulgj1F3VzEjlmus+ISDKFDh7nWB9iG2FcUOUiiZ5BUQWtkEd85PdbIAXt1KHUU3lxwkO8eoLZlentd6YtcX6biLnQiS2leFcnM/vHZQYM=
  app: savingsmatch
  on:
    repo: martin-mcgloin/savingsmatch
