language: groovy
jdk:
  - oraclejdk7

before_script:
  - chmod +x grailsw

script: ./grailsw clean
&& ./grailsw refresh-dependencies
&& ./grailsw “test-app unit:”

before_deploy:
  - chmod +x grailsw

deploy:
provider: heroku
app:
master: savingsmatch
api_key: 46686009-c327-4773-8a29-14474eca21b3
